apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-configure-heroku
spec:
  results:
    - name: serviceurl
      description: service url of the heroku app
  params:
    - name: heroku-details
      description: name of secret containing heroku creds
      default: heroku-details
  steps:
    - name: configure-heroku
      image: pranavbhatia/heroku:0.3
      command: ["/bin/bash"]
      args:
        - -c
        - |
            cat > ~/.netrc << EOF
            machine api.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
            machine git.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API_KEY
            EOF
      envFrom:
        - secretRef:
            name: $(params.heroku-details)
    - name: create-web-app
      image: pranavbhatia/heroku:0.3
      command: ["/bin/bash"]
      args:
        - -c
        - |
            cat ~/.netrc
            git clone https://github.com/prav10194/kubernetes-jenkins && \
            ls -la ./ && \
            cd kubernetes-jenkins/heroku-flask && \
            git config --global user.email "user.name@example.com" && \
            git config --global user.name "User Name" && \
            git init && git add . && git commit -m "Adding files" && \
            heroku create && \
            git push heroku master && heroku ps:scale web=1
            echo $(heroku apps:info -s  | grep web_url | cut -d= -f2 | grep https) | tee $(results.serviceurl.path)
